### ISSUE TITLE
Usage with Fedora?

### ISSUE THREAD

**Issue by Yaikava** [Arc-Compute/libvf.io#14]
Is there any way to use this with Fedora ~~34~~35?

**Comment by arthurrasmusson** [comment]
@mbuchel saw your comment and he's looking into making some patches to support this.

We'll post back here to keep you informed! :)

**Comment by Yaikava** [comment]
Nice :) Thank you

**Comment by arthurrasmusson** [comment]
@Yaikava Just a small update - we're currently working on some .patch files to add support for kernel version 5.14 which is applicable to Fedora 35 I believe. I'll try to keep this thread up to date on our status working on that.

**Comment by mbuchel** [comment]
@Yaikava we got a little update for you, fedora will require a new kernel version with some configuration flags set, we will reach out to the fedora project to see if they are interested in shipping it in the newer versions, otherwise we will need to find a way to enable those configuration options later on.

**Comment by Yaikava** [comment]
👀 I see, Thanks a lot

**Comment by Yaikava** [comment]
Nice 🎉

**Comment by rogerskeie** [comment]
> @Yaikava some great news, we made a patch that allows for work with fedora, we are planning on releasing it sometime over this weekend.

Does this mean it will work with newer kernels on other distros as well?

**Comment by mbuchel** [comment]
yes, we made it work on 5.14/5.15

**Comment by mbuchel** [comment]
quick update, we are aiming to provide support for fedora 35 by the end of this week

**Comment by mbuchel** [comment]
We now support Fedora 35, please use the install-libvfio.sh file in the scripts directory.
