### ISSUE TITLE
PVE support?

### ISSUE THREAD

**Issue by IsaacZD** [Arc-Compute/libvf.io#15]
Hi, I found this awesome project when looking around for a cheap gpu virtualization setup. It looks pretty promising and I am planning maybe give it a try later.

Currently the wiki uses Ubuntu as an example. It would be nice if we can use PVE as host, because I don't want to affect other vms if I did something stupid that crashed Ubuntu. Is there any plan for this on the roadmap?

**Comment by arthurrasmusson** [comment]
I've taken a look at Proxmox and it is something I'm considering trying to build support for! I've heard from a lot of folks like you asking for support so it's definitely moving up my list of priorities given the demand. :)

I'm going to close this issue for now but I'll ping you if we do add support in.

**Comment by mister2d** [comment]
Would love to see this as well!

**Comment by hradec** [comment]
+1 :)

**Comment by cRaZy-bisCuiT** [comment]
Could we do anything to support you by implementing a solution for Proxmox? Maybe you can get in touch with the Proxmox folks as well?

**Comment by bobzer** [comment]
Any update on this ?

**Comment by archenroot** [comment]
@arthurrasmusson - do you have any update on this?
