### ISSUE TITLE
So I'm receiving this error, i'm using the archinstaller 

### ISSUE THREAD

**Issue by burnout01** [Arc-Compute/libvf.io#20]
nvidia-installer log file '/var/log/nvidia-installer.log'
creation time: Fri Dec  3 13:54:42 2021
installer version: 460.73.01

PATH: /home/me/.nimble/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

nvidia-installer command line:
    ./nvidia-installer
    --module-signing-secret-key=/home/me/.ssh/module-private.key
    --module-signing-public-key=/home/me/.ssh/module-public.key
    -q

Unable to load: nvidia-installer ncurses v6 user interface

Unable to load: nvidia-installer ncurses user interface

Using: nvidia-installer ncurses v6 user interface (widechar)
-> Detected 6 CPUs online; setting concurrency level to 6.
ERROR: An NVIDIA kernel module 'nvidia-drm' appears to already be loaded in your kernel.  This may be because it is in use (for example, by an X server, a CUDA program, or the NVIDIA Persistence Daemon), but this may also happen if your >

**Comment by mbuchel** [comment]
you have nvidia installed from before, uninstall it first

**Comment by arthurrasmusson** [comment]
I'm going to close this issue and make a note in the documentation for folks that already have the Nvidia driver installed. If they are a fresh install of their OS that shouldn't happen, but some people might try this on an existing system which is okay too.
