### ISSUE TITLE
Typo in virtio-win filename

### ISSUE THREAD

**Issue by rogerskeie** [Arc-Compute/libvf.io#24]
Should be virtio-win10-prewhql-0.1-161.zip, not vir0tio-win10-prewhql-0.1-161.zip

https://github.com/Arc-Compute/libvf.io/blob/6aa50ade6aa6c620b7a0b1fe93870f87243653dc/scripts/funcs-libvfio.sh#L278

**Comment by AugustNagro** [comment]
After changing this line I can confirm that it's working great on Fedora!

**Comment by mbuchel** [comment]
@ohPaco fixed this typo in the latest push
