### ISSUE TITLE
Add support for systemd-boot

### ISSUE THREAD

**Issue by marte26** [Arc-Compute/LibVF.IO#26]
Right now the script to install libvf.io doesn't support distos that use systemd-boot (like Pop!_OS).
Would it be possibile to add support for it?

**Comment by arthurrasmusson** [comment]
We have a feature push we're going to try to do ahead of FOSDEM 2022 but afterwards I might be able to apply some focus to systemd-boot - at least to get a sense of the scope of changes needed.

In the meantime if anyone does get Pop!_OS to work I'd be glad to get a PR for the install scripts here:
https://github.com/Arc-Compute/libvf.io/blob/master/scripts/install-libvfio.sh
https://github.com/Arc-Compute/libvf.io/blob/master/scripts/funcs-libvfio.sh

**Comment by marte26** [comment]
Ok thanks, I'll see if I can work something out

**Comment by arthurrasmusson** [comment]
@EmanuelW Added Systetmd boot support in his PopOS install script pull request so I'm going to close this issue.
