### ISSUE TITLE
SECOND VM NOT WORKING

### ISSUE THREAD

**Issue by xxevilutionxx** [Arc-Compute/LibVF.IO#28]
hi, i cant open the second vm, always get the same error 
qemu-system-x86_64: warning: Spice: reds.c:2714:reds_init_socket: binding socket to 127.0.0.1:5900 failed
qemu-system-x86_64: warning: Spice: reds.c:3571:do_spice_init: Failed to open SPICE sockets
the yaml files have diferent name for vm and diferent port but not working. 
![Captura de pantalla de 2022-01-01 00-48-39](https://user-images.githubusercontent.com/96936531/147846497-1c8966a3-e4f1-40e1-ac32-b2030c70536d.png)
![Captura de pantalla de 2022-01-01 00-50-04](https://user-images.githubusercontent.com/96936531/147846500-1c676b49-6168-4413-ad99-2853ceb9231c.png)

**Comment by mbuchel** [comment]
you are trying to use 2 nvidia vgpus, there is a limitation in the merged driver currently, you can turn off spice and start intro and nographics and that will create a second vm

**Comment by mbuchel** [comment]
that port is also only for ssh not spice

**Comment by xxevilutionxx** [comment]
se second vm are already done but i cant have active the 2 vm  + looking glass at the same time

**Comment by arthurrasmusson** [comment]
@xxevilutionxx We should be able to fix the port collision by moving the 5900 Spice port into types.nim and declaring it in the yaml as a field the user can alter. We just returned to our normal schedule today so I'll try to spend some time looking into this during this week.

**Comment by arthurrasmusson** [comment]
This issue has been resolved and tested working as of merging feature/spice-disaggregation to master earlier today.
