### ISSUE TITLE
Docs re: remote introspection with parsec/etc.

### ISSUE THREAD

**Issue by johncolby** [Arc-Compute/LibVF.IO#3]
This would be a nice addition to the docs, as I would bet many people looking to partition a GPU would also be looking to run a headless host with multiple clients each accessing a VM with a vGPU. Would parsec work as normal out of the box (I am personally unsure how vGPU interacts with nvenc, for example)? Any particular issues to address in setup?

**Comment by arthurrasmusson** [comment]
Ya, absolutely. All the native GPU encoding functionality should operate normally. I will try to make a note of this in the official documentation.
