### ISSUE TITLE
Is Arch supported?

### ISSUE THREAD

**Issue by cmumme** [Arc-Compute/libvf.io#31]

**Comment by legendcodermartino1245** [comment]
Yes it is

**Comment by arthurrasmusson** [comment]
Yes. Follow the steps detailed in the install guide:
https://arccompute.com/blog/libvfio-commodity-gpu-multiplexing/
In the install script we have a pathway dedicated to when we detect Arch:
https://github.com/Arc-Compute/libvf.io/blob/master/scripts/install-libvfio.sh
