### ISSUE TITLE
install-libvfio.sh hangs while at choosenim step

### ISSUE THREAD

**Issue by starrynightspy** [Arc-Compute/LibVF.IO#52]
![image](https://user-images.githubusercontent.com/34248086/163708739-2d97c093-614d-4ad9-826e-e7a14afb18bb.png)

Installer hangs at this step. I've tried installing choosenim separately after the fact to see if it was an issue specifically with the scripts in this repo, and it still failed. 

So it sounds like choosenim is a tad broken, but I've been asked to open an issue so we can explore alternatives. Choosenim doesn't seem to have much activity on their repo so I'm unsure if this an issue that will get solved quickly on their end.

Running Ubuntu 20.04 fresh install with just Steam, Discord, and Chromium loaded.

**Comment by arthurrasmusson** [comment]
I think we're going to switch to installing binaries rather than compiling on install. Choosenim has been problematic for folks a few times so it seems like ditching it may be the best way to improve reliability during install.

**Comment by starrynightspy** [comment]
If anyone runs across this problem, it's something to do with IPv6. You can disable on Ubuntu (where this seems to happen) with 

sudo sysctl net.ipv6.conf.all.disable_ipv6=1

then run the install again.
