### ISSUE TITLE
Is there a way to use this under Kubernetes?

### ISSUE THREAD

**Issue by unikzforce** [Arc-Compute/LibVF.IO#54]
Hi ArcCompute team,

Is there a way to use this VGpu solution under kubernetes?

By Kubernetes specially I mean Kubevirt.io

Bests,

**Comment by arthurrasmusson** [comment]
We've done this so far as a user API:
https://libvf.io/example/vfscript/docker.yaml
https://openmdev.io/index.php/LibVF.IO#VFScript

It may be possible to do similar things with Kubernetes. If you'd like to help with development on a feature like this you can join our Discord and talk with us in the #Develpoment channel.
