### ISSUE TITLE
I have some error in install script

### ISSUE THREAD

**Issue by bluesiboy** [Arc-Compute/LibVF.IO#55]
![Screenshot_20220519_184957](https://user-images.githubusercontent.com/9855885/169473149-57b9672a-561f-4268-b8fb-9904c2982c05.png)
`Operating System: Arch Linux`
`KDE Plasma Version: 5.24.5`
`KDE Frameworks Version: 5.94.0`
`Qt Version: 5.15.4`
`Kernel Version: 5.17.8-arch1-1 (64-bit)`
`Graphics Platform: X11`
`Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor`
`Memory: 31.3 GiB of RAM`
`Graphics Processor: AMD Radeon RX 580 Series`

**Comment by arthurrasmusson** [comment]
Unfortunately we don't currently provide support for your specific Graphics Processor hardware. You can see which devices are supported here:
https://openmdev.io/index.php/GPU_Support

We would love to see better support for AMD GPU devices. If you'd like that too one option is you can reach out to AMD and express your interest in improved support for LibVF.IO. :)
