### ISSUE TITLE
initial arcd deploy failing due to missing introspection-installations.rom

### ISSUE THREAD

**Issue by matt22207** [Arc-Compute/libvf.io#6]
https://github.com/Arc-Compute/libvf.io/blob/a3cacab9115e4458ddb895c55bf3232122179a5a/scripts/install.sh#L66

This line is failing because introspection-installations.rom has not been created yet. I ran the `arcd deloy` line after line 97 creates the rom, and it seems to work fine.

**Comment by arthurrasmusson** [comment]
@matt22207 Are you using Arch? There is a known issue with the line `makensis installer.nsi` in scripts/install-arch.sh. I think this may be due to a difference between the **makensis** utility on Arch and the equivalent utility on Ubuntu although I think to confirm this I will need to run a few more test installs on Arch.

**Comment by arthurrasmusson** [comment]
@matt22207 Which version of Ubuntu and LibVF.IO are you on? Also would you mind sharing your motherboard model, CPU vendor and model, as well as your GPU model?

Finally would you mind running this script and sharing the output here?
#!/bin/bash
```
for d in /sys/kernel/iommu_groups/*/devices/*; do
  n=${d#*/iommu_groups/*}; n=${n%%/*}
  printf 'IOMMU Group %s ' "$n"
  lspci -nns "${d##*/}"
done
```

All of that information would be very useful in helping narrow the scope of where our problem might reside. Thanks for posting this issue.

**Comment by matt22207** [comment]
@arthurrasmusson .. requested info:

- OS: Ubuntu 21.10 x86_64
- Kernel: 5.13.0-20-generic
- Host: Razer Blade 15 Advanced Model (Early 2020) - RZ09-033 5.04
- CPU: Intel i7-10875H (16) @ 5.100GHz
- GPU: NVIDIA GeForce RTX 2080 SUPER Mobile / Max-Q
- GPU: Intel CometLake-H GT2 [UHD Graphics]

I wasn't able to tell in my bios what motherboard this is. 

For LibVF.IO version, I cloned the repo on `master` as of Oct 24.

IOMMU Groups:

> IOMMU Group 0 00:00.0 Host bridge [0600]: Intel Corporation 10th Gen Core Processor Host Bridge/DRAM Registers [8086:9b44] (rev 02)
> IOMMU Group 10 00:1d.0 PCI bridge [0604]: Intel Corporation Comet Lake PCI Express Root Port #9 [8086:06b0] (rev f0)
> IOMMU Group 11 00:1d.4 PCI bridge [0604]: Intel Corporation Device [8086:06b4] (rev f0)
> IOMMU Group 12 00:1e.0 Communication controller [0780]: Intel Corporation Comet Lake PCH Serial IO UART Host Controller #0 [8086:06a8]
> IOMMU Group 13 00:1f.0 ISA bridge [0601]: Intel Corporation Comet Lake LPC Controller [8086:068d]
> IOMMU Group 13 00:1f.3 Audio device [0403]: Intel Corporation Comet Lake PCH cAVS [8086:06c8]
> IOMMU Group 13 00:1f.4 SMBus [0c05]: Intel Corporation Comet Lake PCH SMBus Controller [8086:06a3]
> IOMMU Group 13 00:1f.5 Serial bus controller [0c80]: Intel Corporation Comet Lake PCH SPI Controller [8086:06a4]
> IOMMU Group 14 02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5260 PCI Express Card Reader [10ec:5260] (rev 01)
> IOMMU Group 15 03:00.0 Non-Volatile memory controller [0108]: Lite-On Technology Corporation Device [14a4:3500] (rev 01)
> IOMMU Group 16 04:00.0 PCI bridge [0604]: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018] [8086:15e7] (rev 06)
> IOMMU Group 17 05:00.0 PCI bridge [0604]: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018] [8086:15e7] (rev 06)
> IOMMU Group 18 05:01.0 PCI bridge [0604]: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018] [8086:15e7] (rev 06)
> IOMMU Group 19 05:02.0 PCI bridge [0604]: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018] [8086:15e7] (rev 06)
> IOMMU Group 1 00:01.0 PCI bridge [0604]: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 02)
> IOMMU Group 1 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104M [GeForce RTX 2080 SUPER Mobile / Max-Q] [10de:1e93] (rev a1)
> IOMMU Group 1 01:00.1 Audio device [0403]: NVIDIA Corporation TU104 HD Audio Controller [10de:10f8] (rev a1)
> IOMMU Group 1 01:00.2 USB controller [0c03]: NVIDIA Corporation TU104 USB 3.1 Host Controller [10de:1ad8] (rev a1)
> IOMMU Group 1 01:00.3 Serial bus controller [0c80]: NVIDIA Corporation TU104 USB Type-C UCSI Controller [10de:1ad9] (rev a1)
> IOMMU Group 20 06:00.0 System peripheral [0880]: Intel Corporation JHL7540 Thunderbolt 3 NHI [Titan Ridge 2C 2018] [8086:15e8] (rev 06)
> IOMMU Group 21 3c:00.0 USB controller [0c03]: Intel Corporation JHL7540 Thunderbolt 3 USB Controller [Titan Ridge 2C 2018] [8086:15e9] (rev 06)
> IOMMU Group 2 00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05)
> IOMMU Group 3 00:04.0 Signal processing controller [1180]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem [8086:1903] (rev 02)
> IOMMU Group 4 00:12.0 Signal processing controller [1180]: Intel Corporation Comet Lake PCH Thermal Controller [8086:06f9]
> IOMMU Group 5 00:14.0 USB controller [0c03]: Intel Corporation Comet Lake USB 3.1 xHCI Host Controller [8086:06ed]
> IOMMU Group 5 00:14.2 RAM memory [0500]: Intel Corporation Comet Lake PCH Shared SRAM [8086:06ef]
> IOMMU Group 6 00:14.3 Network controller [0280]: Intel Corporation Comet Lake PCH CNVi WiFi [8086:06f0]
> IOMMU Group 7 00:15.0 Serial bus controller [0c80]: Intel Corporation Comet Lake PCH Serial IO I2C Controller #0 [8086:06e8]
> IOMMU Group 8 00:16.0 Communication controller [0780]: Intel Corporation Comet Lake HECI Controller [8086:06e0]
> IOMMU Group 9 00:1b.0 PCI bridge [0604]: Intel Corporation Device [8086:06af] (rev f0)

**Comment by arthurrasmusson** [comment]
>OS: Ubuntu 21.10 x86_64
>Kernel: 5.13.0-20-generic

@matt22207 unfortunately this is the problem. Right now we don't have support for kernel version 5.13 with Nvidia graphics. We can support 5.10 and 5.11, we also have a patch file for 5.12 in the /patches/ folder (https://github.com/Arc-Compute/libvf.io/blob/master/patches/twelve.patch) however we haven't tested that enough to guarantee it works well.
I suggest for now if you want to use LibVF.IO that you install Ubuntu 20.04 LTS. We'll try our best to support newer kernel versions in the future. :)

**Comment by arthurrasmusson** [comment]
I'm going to close this issue since I'm fairly sure this was due to the use of an unsupported kernel version.

**Comment by matt22207** [comment]
Thanks @arthurrasmusson . Understood about not supporting kernel 5.13 (yet).

That said, can you please clarify why you feel this is related to the kernel?  During my initial attempt, I thought this was related to the order of the lines in the install.sh script.

For example, everything works fine if I move the `arcd deploy` command to be after the `mkisofs` and `cp introspection-installations.rom ~/.config/arc/`) .. This is because `arcd deploy` expects that rom, so you need to generate it first.

Maybe I'm missing something or moving the deploy line down breaks something else, but wanted to get some additional clarification on your thoughts here. 

Thanks!
