### ISSUE TITLE
What API does it support in windows Virtual machine?

### ISSUE THREAD

**Issue by brane-theory** [Arc-Compute/LibVF.IO#64]
just take GPU-Z for example
if I passthrough RTX 2060 to a windows virtual machine
gpu-z will show that it supports  
<img width="284" alt="image" src="https://user-images.githubusercontent.com/61408487/228127785-7d03928f-7a9f-4d4c-bd8a-d9294091cdde.png">
all the features are available

if I use LibVF.IO
will the features all be supported in windows VM ?
many games need direcx12, pytorch need CUDA, and some other applications need OpenCL, OpenGL and so on.
I have used Vmware Workstation in linux, and the windows guest only supports direcx11, other API support is also very bad.
(I will not pay even a cent to Nvidia grid license

**Comment by arthurrasmusson** [comment]
See [issues/56](https://github.com/Arc-Compute/LibVF.IO/issues/56). Otherwise the APIs you mention are supported.
