### ISSUE TITLE
How is Intel DG1 supported?

### ISSUE THREAD

**Issue by ky-bd** [Arc-Compute/LibVF.IO#67]
Recently I got a DG1 graphics card which is the same model as this [level1techs post](https://forum.level1techs.com/t/libvf-io-a-commodity-gpu-multiplexing-tool-driven-by-vfio-yaml/177192/12). The post seems written by @arthurrasmusson claiming that DG1 is supported. I'm using this card on a Proxmox host, however the install-libvfio.sh script is not happy with it. The script tries to uninstall proxmox-ve and other Proxmox packages when installing its own dependencies, so unfortunately I'm not able to try this fantastic project. 

According to [an Intel community post](https://community.intel.com/t5/Graphics/DG1-QuickSync-and-SR-IOV/td-p/1353656) and [an Intel graphics virtulization support page](https://www.intel.com/content/www/us/en/support/articles/000093216/graphics.html), DG1 might have SR-IOV supoort, but `lspci -v` command didn't list the corresponding PCIe capability, and for the `lspci -xxxx` output, the extended PCIe capabilities part didn't seem to comply with it's [hardware specifications](https://www.intel.com/content/www/us/en/docs/graphics-for-linux/developer-reference/1-0/hardware-specs.html) (either Iris Xe or Iris Xe Max, Volume 2c: Command Reference: Registers). It makes me pretty confused.

So the question is, how does this project support DG1? Is it through SR-IOV & VF passthrough or mdev & GVT-g?

Edit: Add `lspci -v` output:
```sh
VGA compatible controller: Intel Corporation DG1 [Iris Xe Graphics] (rev 01) (prog-if 00 [VGA controller])
        Subsystem: ASUSTeK Computer Inc. Device 8000
        Flags: bus master, fast devsel, latency 0, IOMMU group 9
        Memory at d1000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 3aff00000000 (64-bit, prefetchable) [size=4G]
        Expansion ROM at d2000000 [disabled] [size=2M]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [ac] MSI: Enable- Count=1/1 Maskable+ 64bit+
        Capabilities: [d0] Power Management version 3
        Capabilities: [100] Latency Tolerance Reporting
        Kernel modules: i915
```

**Comment by arthurrasmusson** [comment]
Hey @ky-bd. I bought that unit for testing but I think the SR-IOV drivers in question have only been released for DG2 devices. Recently I've been using the [DG2-512](https://www.techpowerup.com/gpu-specs/intel-dg2-512.g1006)-based [Flex 170](https://www.intel.ca/content/www/ca/en/products/sku/230019/intel-data-center-gpu-flex-170/specifications.html) GPU with great results (very similar to the [A770](https://www.intel.ca/content/www/ca/en/products/sku/229151/intel-arc-a770-graphics-16gb/specifications.html)). 
As for Proxmox I don't think we've ever supported that with LibVF.IO - but per Flex documentation I have managed to get the 170 working with Libvirt which I believe is the base for Proxmox. The driver itself is basically just a DKMS module for SR-IOV on Xe-HPG while SR-IOV for Xe is upstream in-kernel. This should be the simplest possible setup since for some devices (embedded) there's no install required at all and soon that should apply to their dGPUs as well.

**Comment by mbuchel** [comment]
none of the intel SR-IOV code is upstreamed into the kernel, just checked

https://github.com/torvalds/linux/tree/master/drivers/gpu/drm/i915 (this is currently version 6.3 of the kernel)
https://github.com/intel/gvt-linux/issues/160

sadly the DG1 is not supportable with GVT-g as they have no formal plan to, the SR-IOV code for interacting with the driver is not upstreamed into the linux kernel and likely will not be for a while to come.

if you find a solution that allows you to use the DG1, we encourage you to provide a tutorial on how to accomplish this.

the support we offer in libvf.io is through the use of mdevs/GVT-g.

for flex series cards we do have support through the gvm-mgr project specifically. you can than pass through the pci id into the requested gpu for libvf.io.

hopefully this answers the questions you may have here.

**Comment by arthurrasmusson** [comment]
In the context of Intel, gvm-mgr is simply a wrapper for sysfs. Either way you will require Intel's SR-IOV driver.

You can also just echo those values to sysfs yourself [like this](https://pastebin.com/ZgA904h9).

**Comment by ky-bd** [comment]
Thanks for your reply!

> Hey @ky-bd. I bought that unit for testing but I think the SR-IOV drivers in question have only been released for DG2 devices. Recently I've been using the [DG2-512](https://www.techpowerup.com/gpu-specs/intel-dg2-512.g1006)-based [Flex 170](https://www.intel.ca/content/www/ca/en/products/sku/230019/intel-data-center-gpu-flex-170/specifications.html) GPU with great results (very similar to the [A770](https://www.intel.ca/content/www/ca/en/products/sku/229151/intel-arc-a770-graphics-16gb/specifications.html) *see more on how Intel's GPU [FSP](https://doc.coreboot.org/soc/intel/fsp/index.html) may differ between DG-based devices in [GPU Firmware on Open-IOV](https://open-iov.org/index.php/GPU_Firmware#Firmware_Images) - SR-IOV on Arc GPUs may require re-configuration using [FSP Tools](https://github.com/tianocore/edk2/tree/master/IntelFsp2Pkg/Tools/ConfigEditor)). As for Proxmox I don't think we've ever supported that with LibVF.IO - but per Flex documentation I have managed to get the 170 working with Libvirt which I believe is the base for Proxmox. The driver itself is basically just a DKMS module for SR-IOV on Xe-HPG while SR-IOV for Xe is upstream in-kernel (as of kernel 6.1). This should be the simplest possible setup since for some devices (embedded) there's no install required at all and soon that should apply to their dGPUs as well.

I'll look into the FSP and the firmware part. Hope Intel didn't block SR-IOV support there.

---

> none of the intel SR-IOV code is upstreamed into the kernel, just checked
> 
> https://github.com/torvalds/linux/tree/master/drivers/gpu/drm/i915 (this is currently version 6.3 of the kernel) [intel/gvt-linux#160](https://github.com/intel/gvt-linux/issues/160)
> 
> sadly the DG1 is not supportable with GVT-g as they have no formal plan to, the SR-IOV code for interacting with the driver is not upstreamed into the linux kernel and likely will not be for a while to come.
> 
> if you find a solution that allows you to use the DG1, we encourage you to provide a tutorial on how to accomplish this.
> 
> the support we offer in libvf.io is through the use of mdevs/GVT-g.
> 
> for flex series cards we do have support through the gvm-mgr project specifically. you can than pass through the pci id into the requested gpu for libvf.io.
> 
> hopefully this answers the questions you may have here.

Yes, there's a [strongtz/i915-sriov-dkms](https://github.com/strongtz/i915-sriov-dkms) project, which builds a DKMS module out of the [i915 driver from Intel's own kernel](https://github.com/intel/linux-intel-lts/tree/lts-v6.1.8-linux-230201T082419Z/drivers/gpu/drm/i915). However, even in Intel's code, DG1 is not marked as _has_sriov_ (on the contrary, Tiger Lake and Alder Lake iGPU have [this property](https://github.com/intel/linux-intel-lts/blob/lts-v6.1.8-linux-230201T082419Z/drivers/gpu/drm/i915/i915_pci.c#L1006)).

Furthermore, I added some custom logging to the i915-sriov-dkms, and found that actually DG1 is reported as _not an SR-IOV PF_ by the kernel pci driver (got negative result [here](https://github.com/strongtz/i915-sriov-dkms/blob/master/drivers/gpu/drm/i915/i915_sriov.c#L153)). So I guess it's more of a problem with DG1's PCIe extended capabilities, instead of the i915 driver. I post this to the [Intel communities](https://community.intel.com/t5/Graphics/DG1-Xe-and-Xe-MAX-s-PCIe-extended-capabilities-don-t-comply-with/m-p/1474669).

Yes, this answers my question. I'll continue invesigating DG1 and provide more info here if I find some solution. Thank you two for the help.
